# Generated by Django 4.1.1 on 2022-10-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img/', verbose_name='Imagen'),
        ),
    ]
