# Generated by Django 4.1.1 on 2022-10-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_libro_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='image',
            field=models.ImageField(null=True, upload_to='static/img/', verbose_name='Imagen'),
        ),
    ]
